package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Daemon.Worker;
import javax.swing.JOptionPane;
/**
 *
 * @author riyaarora
 */
public class Game extends javax.swing.JFrame {
    int pScore = 0;
    int cScore = 0;
    /**
     * Creates new form Game
     */
    public Game() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        Computer = new javax.swing.JLabel();
        cRoll = new javax.swing.JLabel();
        pRoll = new javax.swing.JLabel();
        Losses = new javax.swing.JLabel();
        Wins = new javax.swing.JLabel();
        Player = new javax.swing.JLabel();
        rollButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 367));
        setSize(new java.awt.Dimension(550, 367));
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Dice Game");
        getContentPane().add(title);
        title.setBounds(210, 10, 130, 40);

        Computer.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Computer.setForeground(new java.awt.Color(255, 255, 255));
        Computer.setText("PC");
        getContentPane().add(Computer);
        Computer.setBounds(410, 80, 30, 20);

        cRoll.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        cRoll.setForeground(new java.awt.Color(255, 255, 255));
        cRoll.setText("Roll");
        getContentPane().add(cRoll);
        cRoll.setBounds(400, 140, 70, 100);

        pRoll.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        pRoll.setForeground(new java.awt.Color(255, 255, 255));
        pRoll.setText("Roll");
        getContentPane().add(pRoll);
        pRoll.setBounds(90, 150, 70, 100);

        Losses.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Losses.setForeground(new java.awt.Color(255, 255, 255));
        Losses.setText("0");
        getContentPane().add(Losses);
        Losses.setBounds(450, 80, 90, 20);

        Wins.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Wins.setForeground(new java.awt.Color(255, 255, 255));
        Wins.setText("0");
        getContentPane().add(Wins);
        Wins.setBounds(150, 80, 120, 20);

        Player.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Player.setForeground(new java.awt.Color(255, 255, 255));
        Player.setText("You");
        getContentPane().add(Player);
        Player.setBounds(100, 80, 40, 20);

        rollButton.setText("Roll");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rollButton);
        rollButton.setBounds(230, 290, 75, 29);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(20, 290, 75, 29);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -1, 550, 367);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        Worker worker = new Worker();
        int pRollVal = worker.randomRoll();
        int cRollVal = worker.randomRoll();
        
        pRoll.setText(Integer.toString(pRollVal));
        cRoll.setText(Integer.toString(cRollVal));
        
        if(worker.decideWinner(pRollVal, cRollVal)){
            pScore++;
        }else{
            cScore++;
        }
        
        Wins.setText(Integer.toString(pScore));
        Losses.setText(Integer.toString(cScore));
        if(pScore + cScore == 11){
            if(worker.checkGameWinner(pScore, cScore)){
                JOptionPane.showMessageDialog(null, "You won!!!");
            }else{
                JOptionPane.showMessageDialog(null, "PC won. :(");
            }
            java.awt.EventQueue.invokeLater(() -> {//restart game
                new Game().setVisible(true);
            });
            this.dispose();
        }
    }//GEN-LAST:event_rollButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {//go to intro
            new IntroPage().setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Computer;
    private javax.swing.JLabel Losses;
    private javax.swing.JLabel Player;
    private javax.swing.JLabel Wins;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cRoll;
    private javax.swing.JLabel pRoll;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
